"""Prompts are versioned artifacts with content hashes (W6-15).

Every ``pir_documents`` row records ``prompt_version`` **and**
``prompt_sha256``, so any PIR in the database can be regenerated byte-identically
-- and, more importantly, so a change to a prompt is visible as a change.

**A version string can lie; a content hash cannot.** Editing a prompt without
bumping its version is the single easiest way to make an eval corpus
meaningless: every stored result claims to come from `v2.1.0` and three of them
came from a different `v2.1.0`. The registry file records the hash, the loader
checks it, and week 7's CI gate goes red when a prompt edit lands without a
version bump (B-11).
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path

import yaml

PROMPTS_DIR = Path(__file__).parent
REGISTRY_PATH = PROMPTS_DIR / "registry.yaml"


class PromptIntegrityError(RuntimeError):
    """The file on disk is not the file the registry describes."""


@dataclass(frozen=True, slots=True)
class Prompt:
    role: str
    version: str
    path: Path
    body: str
    sha256: str

    def render(self, **values: object) -> str:
        """Fill the template.

        ``str.format`` with doubled braces in the file, so the JSON examples
        survive intact -- the examples are the part a model actually imitates,
        and a template engine that mangled them would quietly degrade output
        quality in a way no test would catch.
        """
        return self.body.format(**values)


def sha256_of(text: str) -> str:
    """Hash the **normalized** text.

    Line endings are normalized first. Without that, a Windows checkout and a
    Linux CI runner compute different hashes for an identical prompt, and the
    integrity check fails for everyone on one of the two platforms -- which is
    exactly the kind of correct-looking guard that gets disabled instead of
    fixed.
    """
    return hashlib.sha256(text.replace("\r\n", "\n").encode("utf-8")).hexdigest()


def load_registry(path: Path | None = None) -> dict[str, Prompt]:
    """Read ``registry.yaml`` and verify every prompt's hash."""
    registry_path = path or REGISTRY_PATH
    raw = yaml.safe_load(registry_path.read_text(encoding="utf-8")) or {}

    out: dict[str, Prompt] = {}
    for role, entry in (raw.get("prompts") or {}).items():
        file_path = registry_path.parent / str(entry["file"])
        body = file_path.read_text(encoding="utf-8")
        actual = sha256_of(body)
        declared = str(entry["sha256"])

        if actual != declared:
            raise PromptIntegrityError(
                f"{file_path.name} does not match its registry entry.\n"
                f"  declared: {declared}\n"
                f"  actual:   {actual}\n"
                "A prompt changed without its version and hash being updated. "
                "Bump the version in registry.yaml and record the new hash -- "
                "every stored PIR claims a prompt version, and two different "
                "prompts under one version make the eval corpus meaningless."
            )

        out[str(role)] = Prompt(
            role=str(role),
            version=str(entry["version"]),
            path=file_path,
            body=body,
            sha256=actual,
        )
    return out


def get_prompt(role: str, path: Path | None = None) -> Prompt:
    prompts = load_registry(path)
    if role not in prompts:
        raise KeyError(f"no prompt registered for role {role!r} (have {sorted(prompts)})")
    return prompts[role]
